# Generated by Django 2.2 on 2021-08-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_vehicle',
            new_name='customer_vehicle_model',
        ),
    ]
