# Generated by Django 2.2 on 2021-08-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicle', '0002_auto_20210826_1801'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_vehicle_model',
            table='customer_vehicle_model',
        ),
    ]
