# Generated by Django 2.2 on 2021-08-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicle', '0003_auto_20210829_0008'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_vehicle_model',
            table='vehicletable',
        ),
    ]
