# Generated by Django 2.2 on 2021-08-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicle', '0004_auto_20210829_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_vehicle_model',
            new_name='Vehicle',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
