# Generated by Django 2.2 on 2021-08-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicle', '0007_auto_20210829_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
