# Generated by Django 2.2 on 2021-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicle', '0009_auto_20210829_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
