# Generated by Django 2.2 on 2021-08-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_vehicle', '0012_auto_20210829_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_service_date',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_date',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
